/*
INTEGRANTES
Ariel Fernandes 1700760
Thiago Roldão 1520133
Gabriel Chaves 1700727
Vitor Freitas 1700741
Maria Cecilia 1700785
*/

CREATE DATABASE ImpactaTOP
GO
USE ImpactaTOP
GO
CREATE TABLE Curso(
		ID_Curso INT not null PRIMARY KEY IDENTITY(1,1),
		SIGLA VARCHAR(5) not null,
		NOME VARCHAR(50) not null,
        CONSTRAINT uqCurso UNIQUE (SIGLA),
        CONSTRAINT uqCurso1 UNIQUE (NOME)
		);

CREATE TABLE Aluno(
		ID_Aluno INT not null PRIMARY KEY IDENTITY(1,1),
		RA INT not null UNIQUE,
		NOME VARCHAR(120) not null,
		EMAIL VARCHAR(80) not null,
		CELULAR CHAR(11) not null,
		SIGLA_CURSO CHAR(2) not null,
		);

CREATE TABLE Disciplina(
		ID_Disciplina INT not null PRIMARY KEY IDENTITY(1,1), 
		NOME VARCHAR(240) not null,
		CARGA_HORARIA TINYINT not null,
		TEORIA DECIMAL(3) not null,
		PRATICA DECIMAL(3) not null,
		EMENTA TEXT not null,
		COMPETENCIAS TEXT not null,
		HABILIDADES TEXT not null,
		CONTEUDO TEXT not null,
		BIBLIOGRAFIA_BASICA TEXT not null,
		BIBLIOGRAFIA_COMPLEMENTAR TEXT not null,
        CONSTRAINT uqDisciplina UNIQUE (NOME)
		);

CREATE TABLE Professor(
		ID_Professor INT not null PRIMARY KEY IDENTITY(1,1),
		RA INT not null,
		APELIDO VARCHAR(30) not null UNIQUE,
		NOME VARCHAR(120) not null,
		EMAIL VARCHAR(80) not null,
		CELULAR CHAR(11) not null,
        CONSTRAINT uqProfessor1 UNIQUE (RA),
        CONSTRAINT uqProfessor UNIQUE (APELIDO)
		);

CREATE TABLE GradeCurricular(
		ID_GradeC INT not null PRIMARY KEY IDENTITY(1,1),
		SIGLA_CURSO VARCHAR(5) not null,
		ANO SMALLINT not null,
		SEMESTRE CHAR(1) not null,
        CONSTRAINT uqGradeCurricular UNIQUE (ANO, SEMESTRE),
        FOREIGN KEY(SIGLA_CURSO) REFERENCES Curso(SIGLA)
		);

CREATE TABLE Periodo(
		ID_Periodo INT not null PRIMARY KEY IDENTITY(1,1),
		SIGLA_CURSO VARCHAR(5) not null,
		ANO_GRADE SMALLINT not null,
		SEMESTRE_GRADE CHAR(1) not null,
		NUMERO TINYINT not null,
        CONSTRAINT uqPeriodo UNIQUE (NUMERO),
        FOREIGN KEY(SIGLA_CURSO) REFERENCES Curso(SIGLA),
        FOREIGN KEY(ANO_GRADE, SEMESTRE_GRADE) REFERENCES GradeCurricular(ANO, SEMESTRE),
		);

CREATE TABLE PeriodoDisciplina(
		ID_PeriodoD INT not null PRIMARY KEY IDENTITY(1,1),
		SIGLA_CURSO VARCHAR(5) not null,
		ANO_GRADE SMALLINT not null,
		SEMESTRE_GRADE CHAR(1) not null,
		NUMERO_PERIODO TINYINT not null,
		NOME_DISCIPLINA VARCHAR(240) not null,
        FOREIGN KEY(SIGLA_CURSO) REFERENCES Curso(SIGLA),
        FOREIGN KEY(ANO_GRADE, SEMESTRE_GRADE) REFERENCES GradeCurricular(ANO, SEMESTRE),
        FOREIGN KEY(NUMERO_PERIODO) REFERENCES Periodo(NUMERO),
        FOREIGN KEY(NOME_DISCIPLINA) REFERENCES Disciplina(NOME)
		);

CREATE TABLE DisciplinaOfertada(
		ID_DisciplinaO INT not null PRIMARY KEY IDENTITY(1,1),
		NOME_DISCIPLINA VARCHAR(240) not null,
		ANO SMALLINT not null,
		SEMESTRE CHAR(1) not null,
		CONSTRAINT uqDisciplinaOfertada UNIQUE (ANO, SEMESTRE),
        FOREIGN KEY(NOME_DISCIPLINA) REFERENCES Disciplina(NOME)
		);
        
CREATE TABLE Turma(
		ID_Turma INT not null PRIMARY KEY IDENTITY(1,1),
		NOME_DISCIPLINA VARCHAR(240) not null,
		ANO_OFERTADO SMALLINT not null,
		SEMESTRE_OFERTADO CHAR(1) not null,
		ID CHAR(1) not null	UNIQUE,
		TURNO VARCHAR(15) not null,
		RA_PROFESSOR INT not null,
        FOREIGN KEY(NOME_DISCIPLINA) REFERENCES Disciplina(NOME),
        FOREIGN KEY(ANO_OFERTADO, SEMESTRE_OFERTADO) REFERENCES DisciplinaOfertada(ANO, SEMESTRE),
        FOREIGN KEY(RA_PROFESSOR) REFERENCES Professor(RA)
		);

CREATE TABLE CursoTurma(
		ID_CursoT INT not null PRIMARY KEY IDENTITY(1,1),
		SIGLA_CURSO VARCHAR(5) not null,
		NOME_DISCIPLINA VARCHAR(240) not null,
		ANO_OFERTADO SMALLINT not null,
		SEMESTRE_OFERTADO CHAR(1) not null,
		ID_TURMA CHAR(1) not null,
        FOREIGN KEY(SIGLA_CURSO) REFERENCES Curso(SIGLA),
        FOREIGN KEY(NOME_DISCIPLINA) REFERENCES Disciplina(NOME),
        FOREIGN KEY(ANO_OFERTADO, SEMESTRE_OFERTADO) REFERENCES DisciplinaOfertada(ANO, SEMESTRE),
        FOREIGN KEY(ID_TURMA) REFERENCES Turma(ID)
		);

CREATE TABLE Questao(
		ID_Questão INT not null PRIMARY KEY IDENTITY(1,1),
		NOME_DISCIPLINA VARCHAR(240) not null,
		ANO_OFERTADO SMALLINT not null,
		SEMESTRE_OFERTADO CHAR(1) not null,
		ID_TURMA CHAR(1) not null,
		NUMERO INT not null UNIQUE,
		DATA_LIMITE_ENTREGA DATE not null,
		DESCRICAO TEXT not null,
		DATA DATE not null,
        FOREIGN KEY(NOME_DISCIPLINA) REFERENCES Disciplina(NOME),
        FOREIGN KEY(ANO_OFERTADO, SEMESTRE_OFERTADO) REFERENCES DisciplinaOfertada(ANO, SEMESTRE),
        FOREIGN KEY(ID_TURMA) REFERENCES Turma(ID)
		);

CREATE TABLE ArquivosQuestao(
		ID_ArquivosQuestao INT not null PRIMARY KEY IDENTITY(1,1),
		NOME_DISCIPLINA VARCHAR(240) not null,
		ANO_OFERTADO SMALLINT not null,
		SEMESTRE_OFERTADO CHAR(1) not null,
		ID_TURMA CHAR(1) not null,
		NUMERO_QUESTAO INT not null,
		ARQUIVO VARCHAR(500) not null UNIQUE,
        FOREIGN KEY(NOME_DISCIPLINA) REFERENCES Disciplina(NOME),
        FOREIGN KEY(ANO_OFERTADO, SEMESTRE_OFERTADO) REFERENCES DisciplinaOfertada(ANO, SEMESTRE),
        FOREIGN KEY(ID_TURMA) REFERENCES Turma(ID),
        FOREIGN KEY(NUMERO_QUESTAO) REFERENCES Questao(NUMERO)
		);

CREATE TABLE Matricula(
		ID_Matricula INT not null PRIMARY KEY IDENTITY(1,1),
		RA_ALUNO INT not null,
		NOME_DISCIPLINA VARCHAR(240) not null,
		ANO_OFERTADO SMALLINT not null,
		SEMESTRE_OFERTADO CHAR(1) not null ,
		ID_TURMA CHAR(1) not null,
        FOREIGN KEY(RA_ALUNO) REFERENCES Aluno(RA),
        FOREIGN KEY(NOME_DISCIPLINA) REFERENCES Disciplina(NOME),
        FOREIGN KEY(ANO_OFERTADO, SEMESTRE_OFERTADO) REFERENCES DisciplinaOfertada(ANO, SEMESTRE),
        FOREIGN KEY(ID_TURMA) REFERENCES Turma(ID)
		);

CREATE TABLE Resposta(
		ID_Resposta INT not null PRIMARY KEY IDENTITY(1,1),
		NOME_DISCIPLINA VARCHAR(240) not null,
		ANO_OFERTADO SMALLINT not null,
		SEMESTRE_OFERTADO CHAR(1) not null,
		ID_TURMA CHAR(1) not null,
		NUMERO_QUESTAO INT not null,
		RA_ALUNO INT not null UNIQUE,
		DATA_AVALIACAO DATE not null,
		NOTA DECIMAL(4,2) not null,
		AVALIACAO TEXT not null,
		DESCRICAO TEXT not null,
		DATA_DE_ENVIO DATE not null,
        FOREIGN KEY(NOME_DISCIPLINA) REFERENCES Disciplina(NOME),
        FOREIGN KEY(ANO_OFERTADO, SEMESTRE_OFERTADO) REFERENCES DisciplinaOfertada(ANO, SEMESTRE),
        FOREIGN KEY(ID_TURMA) REFERENCES Turma(ID),
        FOREIGN KEY(NUMERO_QUESTAO) REFERENCES Questao(NUMERO)
		);

CREATE TABLE ArquivosResposta(
		ID_ArquivosR INT not null PRIMARY KEY IDENTITY(1,1),
		NOME_DISCIPLINA VARCHAR(240) not null,
		ANO_OFERTADO SMALLINT not null,
		SEMESTRE_OFERTADO CHAR(1) not null,
		ID_TURMA CHAR(1) not null,
		NUMERO_QUESTAO INT not null,
		RA_ALUNO INT not null,
		ARQUIVO VARCHAR(500) not null UNIQUE,
        FOREIGN KEY(NOME_DISCIPLINA) REFERENCES Disciplina(NOME),
        FOREIGN KEY(ANO_OFERTADO, SEMESTRE_OFERTADO) REFERENCES DisciplinaOfertada(ANO, SEMESTRE),
        FOREIGN KEY(ID_TURMA) REFERENCES Turma(ID),
        FOREIGN KEY(NUMERO_QUESTAO) REFERENCES Questao(NUMERO),
        FOREIGN KEY(RA_ALUNO) REFERENCES Resposta(RA_ALUNO)
		);